# Generated by Django 3.1.2 on 2021-03-04 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210304_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
