# Generated by Django 3.2.5 on 2022-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_verify',
        ),
        migrations.AddField(
            model_name='account',
            name='is_email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
