# Generated by Django 3.2.5 on 2022-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sk', models.CharField(max_length=90)),
                ('headline_sk', models.CharField(max_length=100)),
                ('text_sk', models.TextField()),
                ('title_en', models.CharField(max_length=90)),
                ('headline_en', models.CharField(max_length=100)),
                ('text_en', models.TextField()),
                ('title_de', models.CharField(max_length=90)),
                ('headline_de', models.CharField(max_length=100)),
                ('text_de', models.TextField()),
                ('name', models.CharField(max_length=90)),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
