# Generated by Django 3.2.5 on 2022-01-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220108_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='headline_de',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='headline_en',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='headline_sk',
            field=models.CharField(max_length=250),
        ),
    ]
