# Generated by Django 3.2.5 on 2022-01-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220108_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registeruz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico', models.CharField(max_length=90)),
                ('nazovUJ', models.CharField(max_length=90)),
            ],
        ),
    ]
