# Generated by Django 3.2.5 on 2022-01-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_registeruz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucetnizaverka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zaverka', models.CharField(max_length=90)),
                ('ico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.registeruz')),
            ],
        ),
    ]
